debug: true
remove: true
removal_reason: |+
  Hi /u/{username}! Images with text are not allowed on /r/{subreddit}, your post has been removed for containing the following text:
  
  > {text}
  
  *If you believe text was erroneously detected, reply to this comment or [message the moderators](https://www.reddit.com/message/compose?to=%2Fr%2F{subreddit}) for human review.*
human_review: true # Whether the bot will monitor its inbox for replies to the removal reason.
human_review_report: "/u/{username} has disputed this automatic removal. Double check the image for text!"